#!/bin/sh

cwd=$(pwd)

# shellcheck disable=SC2046
cd $(git rev-parse --show-toplevel)/golang || exit 1

while true; do
  fieldalignment -fix  ./...
  if [ $? -eq 0 ]; then
    break
  fi
done

go install golang.org/x/vuln/cmd/govulncheck@latest
govulncheck ./...

go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
golangci-lint run ./...

cd "$cwd" || exit 1