#!/bin/env bash

goVersion=$(go version | grep -o '1\.[0-9]*\.[0-9]*')
# shellcheck disable=SC2206
goVersionArray=(${goVersion//./ })

if [ "${goVersionArray[1]}" -lt 19 ]; then
    echo "Go version must be at least 1.19"
    exit 1
fi

cwd=$(pwd)

# shellcheck disable=SC2046
cd $(git rev-parse --show-toplevel)/golang || exit 1

go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest

# Try 10 times to do fieldalignment
for _ in $(seq 1 10) ; do
  fieldalignment -fix  ./... 2> /dev/null
done

go install golang.org/x/vuln/cmd/govulncheck@latest
if govulncheck ./...; then
  echo "govulncheck: no vulnerabilities found"
else
  echo "Vulnerabilities found"
  exit 1
fi

go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
if golangci-lint run ./...; then
  echo "golangci-lint: no issues found"
else
  echo "Linting failed"
  exit 1
fi


cd "$cwd" || exit 1